/*
 * The MIT License
 *
 * Copyright 2023 JOSEPH EMMANUEL F. TAMAYO.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package Forms;

import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

import EmployeeManagementSystem.*;
import java.awt.Color;
import javax.swing.ImageIcon;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author josep
 */
public class Login extends javax.swing.JFrame {

  private final DependencyInjector di = DependencyInjector.getInstance();
  
  /**
   * Creates new form Login
   */
  public Login() {
    initComponents();
    jLabel1.setForeground(Color.white);
    jLabel2.setForeground(Color.white);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new JLabel();
    txtUsername = new JTextField();
    jLabel2 = new JLabel();
    passwordField = new JPasswordField();
    btnLogin = new JButton();
    btnExit = new JButton();
    jLabel3 = new JLabel();

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    setUndecorated(true);
    getContentPane().setLayout(new AbsoluteLayout());

    jLabel1.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
    jLabel1.setText("Username:");
    getContentPane().add(jLabel1, new AbsoluteConstraints(79, 94, -1, -1));

    txtUsername.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
    getContentPane().add(txtUsername, new AbsoluteConstraints(183, 89, 161, -1));

    jLabel2.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
    jLabel2.setText("Password:");
    getContentPane().add(jLabel2, new AbsoluteConstraints(79, 147, 86, -1));

    passwordField.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
    passwordField.setEchoChar('\u25cf');
    getContentPane().add(passwordField, new AbsoluteConstraints(183, 142, 161, -1));

    btnLogin.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
    btnLogin.setText("Login");
    btnLogin.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        btnLoginActionPerformed(evt);
      }
    });
    getContentPane().add(btnLogin, new AbsoluteConstraints(119, 222, -1, -1));

    btnExit.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
    btnExit.setText("Exit");
    btnExit.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        btnExitActionPerformed(evt);
      }
    });
    getContentPane().add(btnExit, new AbsoluteConstraints(217, 222, -1, -1));

    jLabel3.setIcon(new ImageIcon(getClass().getResource("/Resources/blue-1634110_1280.png"))); // NOI18N
    getContentPane().add(jLabel3, new AbsoluteConstraints(0, 0, 420, 340));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnLoginActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    String username = txtUsername.getText(), password = new String (passwordField.getPassword());
    txtUsername.setText("");
    passwordField.setText("");
    
    // verify the login with the database
    boolean isLoginOK = di.loginFacade().verifyLogin(username, password);
    
    if (isLoginOK) {      
      
//      App.setCurrentRole("user");
      EventQueue.invokeLater(() -> {
          new Main().setVisible(true);
          dispose();
        });
    }
    else {
      JOptionPane.showMessageDialog(this, "Login Failed", "Login", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_btnLoginActionPerformed

  private void btnExitActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    dispose();
  }//GEN-LAST:event_btnExitActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Login().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  JButton btnExit;
  JButton btnLogin;
  JLabel jLabel1;
  JLabel jLabel2;
  JLabel jLabel3;
  JPasswordField passwordField;
  JTextField txtUsername;
  // End of variables declaration//GEN-END:variables
}
