/*
 * The MIT License
 *
 * Copyright 2023 JOSEPH EMMANUEL F. TAMAYO.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package Forms;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultDesktopManager;
import javax.swing.GroupLayout;
import javax.swing.JComponent;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.WindowConstants;

/**
 *
 * @author josep
 */
public class Main extends javax.swing.JFrame {

  private Positions positionsFrame;
  /**
   * Creates new form Main
   */
  public Main() {
    initComponents();
    jDesktopPane1.setDesktopManager(new DefaultDesktopManager() {
      
      @Override
      public void dragFrame(JComponent f, int x, int y) {
        if (f instanceof JInternalFrame) {
          JInternalFrame frame = (JInternalFrame) f;
          JDesktopPane desk = frame.getDesktopPane();
          Dimension d = desk.getSize();

          if (x < 0) {
            x = 0;
          } else {
            if (x + frame.getWidth() > d.width) {
              x = d.width - frame.getWidth();
            }
          }
          if (y < 0) {
            y = 0;
          } else {
            if (y + frame.getHeight() > d.height) {
              y = d.height - frame.getHeight();
            }
          }
        }

        super.dragFrame(f, x, y);
      }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jDesktopPane1 = new JDesktopPane();
    mainMenuBar = new JMenuBar();
    fileMenu = new JMenu();
    employeesListMenuItem = new JMenuItem();
    departmentsMenuItem = new JMenuItem();
    positionsMenuItem = new JMenuItem();
    employeesMenuItem = new JMenuItem();
    jSeparator1 = new JPopupMenu.Separator();
    exitMenuItem = new JMenuItem();
    helpMenu = new JMenu();
    aboutMenuItem = new JMenuItem();

    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    setTitle("Employee Management System");

    jDesktopPane1.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);

    GroupLayout jDesktopPane1Layout = new GroupLayout(jDesktopPane1);
    jDesktopPane1.setLayout(jDesktopPane1Layout);
    jDesktopPane1Layout.setHorizontalGroup(jDesktopPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGap(0, 921, Short.MAX_VALUE)
    );
    jDesktopPane1Layout.setVerticalGroup(jDesktopPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
      .addGap(0, 588, Short.MAX_VALUE)
    );

    getContentPane().add(jDesktopPane1, BorderLayout.CENTER);

    fileMenu.setText("File");

    employeesListMenuItem.setText("List of Employees");
    employeesListMenuItem.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        employeesListMenuItemActionPerformed(evt);
      }
    });
    fileMenu.add(employeesListMenuItem);

    departmentsMenuItem.setText("Departments");
    fileMenu.add(departmentsMenuItem);

    positionsMenuItem.setText("Positions");
    positionsMenuItem.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        positionsMenuItemActionPerformed(evt);
      }
    });
    fileMenu.add(positionsMenuItem);

    employeesMenuItem.setText("Employees");
    fileMenu.add(employeesMenuItem);
    fileMenu.add(jSeparator1);

    exitMenuItem.setText("Exit");
    exitMenuItem.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        exitMenuItemActionPerformed(evt);
      }
    });
    fileMenu.add(exitMenuItem);

    mainMenuBar.add(fileMenu);

    helpMenu.setText("Help");

    aboutMenuItem.setText("About");
    helpMenu.add(aboutMenuItem);

    mainMenuBar.add(helpMenu);

    setJMenuBar(mainMenuBar);

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void employeesListMenuItemActionPerformed(ActionEvent evt) {//GEN-FIRST:event_employeesListMenuItemActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_employeesListMenuItemActionPerformed

  private void positionsMenuItemActionPerformed(ActionEvent evt) {//GEN-FIRST:event_positionsMenuItemActionPerformed
    
    if (positionsFrame == null) {
      positionsFrame = new Positions();

      Dimension desktopSize = jDesktopPane1.getSize();
      Dimension internalFrameSize = positionsFrame.getSize();

      positionsFrame.setLocation(
        (desktopSize.width - internalFrameSize.width) / 2,
        (desktopSize.height - internalFrameSize.height) / 2
      );

      jDesktopPane1.add(positionsFrame);
    }
    else {
      if (positionsFrame.isIcon()) {
        try {
          
          Dimension desktopSize = jDesktopPane1.getSize();
          Dimension internalFrameSize = positionsFrame.getSize();

          positionsFrame.setLocation(
            (desktopSize.width - internalFrameSize.width) / 2,
            (desktopSize.height - internalFrameSize.height) / 2
          );
          
          positionsFrame.setIcon(false);
        } catch (PropertyVetoException ex) {
          Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
      else if (!positionsFrame.isVisible()) {
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension internalFrameSize = positionsFrame.getSize();

        positionsFrame.setLocation(
          (desktopSize.width - internalFrameSize.width) / 2,
          (desktopSize.height - internalFrameSize.height) / 2
        );
        
        positionsFrame.setVisible(true);
      }
    }
  }//GEN-LAST:event_positionsMenuItemActionPerformed

  private void exitMenuItemActionPerformed(ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
    int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    
    if (choice == JOptionPane.YES_OPTION) {
      dispose();
    }
  }//GEN-LAST:event_exitMenuItemActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Main().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  JMenuItem aboutMenuItem;
  JMenuItem departmentsMenuItem;
  JMenuItem employeesListMenuItem;
  JMenuItem employeesMenuItem;
  JMenuItem exitMenuItem;
  JMenu fileMenu;
  JMenu helpMenu;
  JDesktopPane jDesktopPane1;
  JPopupMenu.Separator jSeparator1;
  JMenuBar mainMenuBar;
  JMenuItem positionsMenuItem;
  // End of variables declaration//GEN-END:variables
}
